// final Map<String, dynamic> symptomQuestions = {


  
//   "coughing": {
//     "questions": [
//       "How long has your pet had coughing?",
//       "What type of coughing is it? (Dry, Wet, or Honking)"
//     ],
//     "impactChoices1": ["1-2 days", "3-5 days", "6-10 days", "11+ days"],
//     "impactChoices2": ["dry", "wet", "honking"],
//   },
//   "fever": {
//     "questions": [
//       "How long has your pet had fever?"
//     ],
//     "impactChoices1": ["1-2 days", "3-5 days", "6-10 days", "11+ days"],
//     "impactChoices2": [],
//   },
//   "lethargy": {
//     "questions": [
//       "How long has your pet had lethargy?",
//       "What type of lethargy is it? (Intermittent or Constant)"
//     ],
//     "impactChoices1": ["1-2 days", "3-5 days", "6-10 days", "11+ days"],
//     "impactChoices2": ["intermittent", "constant"],
//   },
//   "sneezing": {
//     "questions": [
//       "How long has your pet had sneezing?",
//       "What type of sneezing is it? (Occasional or Frequent)"
//     ],
//     "impactChoices1": ["1-2 days", "3-5 days", "6-10 days", "11+ days"],
//     "impactChoices2": ["occasional", "frequent"],
//   },
//   "diarrhea": {
//     "questions": [
//       "How long has your pet had diarrhea?",
//       "What type of diarrhea is it? (Watery or Bloody)"
//     ],
//     "impactChoices1": ["1-2 days", "3-5 days", "6-10 days", "11+ days"],
//     "impactChoices2": ["watery", "bloody"],
//   },
//   "nasal discharge": {
//     "questions": [
//       "What type of nasal discharge is it? (Mucus or Bloody)"
//     ],
//     "impactChoices1": ["mucus", "bloody"],
//   },
//   "seizures": {
//     "questions": [
//       "How long has your pet had seizures?",
//       "What type of seizures is it? (Mild, Severe, or Cluster)"
//     ],
//     "impactDays": ["1-2 days", "3-5 days", "6-10 days", "11+ days"],
//     "impactChoices1": ["mild", "severe", "cluster"],
//   },
//   "vomiting": {
//     "questions": [
//       "How long has your pet had vomiting?",
//       "What type of vomiting is it? (Bloody, Foamy, Yellow, or Green)"
//     ],
//     "impactChoices1": ["1-2 days", "3-5 days", "6-10 days", "11+ days"],
//     "impactChoices2": ["bloody", "foamy", "yellow", "green"],
//   },
//   "weight loss": {
//     "questions": [
//       "How long has your pet had weight loss?"
//     ],
//     "impactChoices1": ["1-2 days", "3-5 days", "6-10 days", "11+ days"],
//     "impactChoices2": [],
//   },
//   "breathing difficulty": {
//     "questions": [
//       "How long has your pet had breathing difficulty?",
//       "What type of breathing difficulty is it? (Mild, Severe, or Labored)"
//     ],
//     "impactChoices1": ["1-2 days", "3-5 days", "6-10 days", "11+ days"],
//     "impactChoices2": ["mild", "severe", "labored"],
//   },
//   "loss of appetite": {
//     "questions": [
//       "How long has your pet had loss of appetite?"
//     ],
//     "impactChoices1": ["1-2 days", "3-5 days", "6-10 days", "11+ days"],
//   },
//   "itching": {
//     "questions": [
//       "How long has your pet had itching?",
//       "What type of itching is it? (Localized or Generalized)"
//     ],
//     "impactChoices1": ["1-2 days", "3-5 days", "6-10 days", "11+ days"],
//     "impactChoices2": ["localized", "generalized"],
//   },
//   "ear discharge": {
//     "questions": [
//       "What type of ear discharge is it? (Brown or Bloody)"
//     ],
//     "impactChoices1": ["brown", "bloody"],
//   },
//   "pain": {
//     "questions": [
//       "How long has your pet had pain?",
//       "What type of pain is it? (Sharp, Dull, or Localized)"
//     ],
//     "impactChoices1": ["1-2 days", "3-5 days", "6-10 days", "11+ days"],
//     "impactChoices2": ["sharp", "dull", "localized"],
//   },

//   "eye discharge": {
//     "questions": [
//       "How long has your pet had eye discharge?",
//       "Is the eye discharge Watery or Mucous-like?"
//     ],
//     "impactChoices1": ["1-2 days", "3-10 days"],
//     "impactChoices2": ["watery", "mucous-like"],
//   },

//   "muscle twitching": {
//     "questions": [
//       "How long has your pet had muscle twitching?",
//       "Is the muscle twitching Mild or Severe?"
//     ],
//     "impactChoices1": ["1-2 days", "3-5 days", "6-10 days", "11+ days"],
//     "impactChoices2": ["mild", "severe", "variable"],
//   },
  

//   "muscle paralysis": {
//     "questions": [
//       "How long has your pet had muscle paralysis?",
//       "Is the muscle paralysis Ascending?"
//     ],
//     "impactChoices1": ["1-2 days", "3-5 days", "6-10 days", "11+ days", "irreversible"],
//     "impactChoices2": ["ascending", "irreversible"],
//   },




//   "abdominal discomfort": {},
//   "abdominal enlargement": {},
//   "abdominal pain": {},
//   "abnormal breeding behavior": {},
//   "abnormal posture": {},
//   "abscesses": {},
//   "aggression": {},
//   "anemia": {},
//   "anxiety": {},
//   "arched back": {},
//   "back pain": {},
//   "back stiffness": {},
//   "bad breath": {},
//   "behavioral changes": {},
//   "bleeding": {},
//   "bleeding gums": {},
//   "blindness": {},
//   "bloating": {},
//   "blood in urine": {},
//   "bluish gums": {},
//   "bruising": {},
//   "bunny hopping": {},
//   "cataracts": {},
//   "circling": {},
//   "collapse": {},
//   "confusion": {},
//   "confusion post-seizure": {},
//   "coordination issues": {},
//   "dandruff": {},
//   "dark stool": {},
//   "dark urine": {},
//   "decreased appetite": {},
//   "dehydration": {},
//   "depression": {},
//   "diabetes mellitus": {},
//   "difficulty breathing": {},
//   "difficulty chewing": {},
//   "difficulty eating": {},
//   "difficulty moving": {},
//   "difficulty moving elbow": {},
//   "difficulty opening mouth": {},
//   "difficulty rising": {},
//   "difficulty running": {},
//   "difficulty standing": {},
//   "difficulty swallowing": {},
//   "difficulty urinating": {},
//   "difficulty walking": {},
//   "discolored teeth": {},
//   "disorientation": {},
//   "distended abdomen": {},
//   "draining wounds": {},
//   "drooling": {},
//   "dropping food": {},
//   "dull coat": {},
//   "ear odor": {},
//   "ear scratching": {},
//   "edema (swelling)": {},
//   "enlarged jaw": {},
//   "enlarged lymph nodes": {},
//   "enlarged testicles": {},
//   "excessive bleeding": {},
//   "excessive bleeding from minor wounds": {},
//   "excessive crying": {},
//   "excessive drooling": {},
//   "excessive scratching": {},
//   "exercise intolerance": {},
//   "eye inflammation": {},
//   "facial abnormalities": {},
//   "facial swelling": {},
//   "fainting": {},
//   "falling over": {},
//   "fatigue": {},
//   "fearfulness": {},
//   "flea dirt": {},
//   "fleas": {},
//   "foot dragging": {},
//   "forelimb lameness": {},
//   "frequent urination": {},
//   "gagging": {},
//   "hair loss": {},
//   "head shaking": {},
//   "head tilt": {},
//   "head tremors": {},
//   "hind limb atrophy": {},
//   "hindlimb lameness": {},
//   "hip pain": {},
//   "hoarse bark": {},
//   "hunched back": {},
//   "hypothermia": {},
//   "incontinence": {},
//   "increased appetite": {},
//   "increased thirst": {},
//   "increased urination": {},
//   "inflamed gums": {},
//   "inflammation": {},
//   "intermittent lameness": {},
//   "intermittent limping": {},
//   "irritability": {},
//   "jaundice": {},
//   "jaw pain": {},
//   "joint pain": {},
//   "joint swelling": {},
//   "lameness": {},
//   "light sensitivity": {},
//   "limb swelling": {},
//   "loose teeth": {},
//   "loss of consciousness": {},
//   "loss of coordination": {},
//   "loss of muscle mass": {},
//   "loss of reflexes": {},
//   "mouth ulcers": {},
//   "muscle atrophy": {},
//   "muscle pain": {},
//   "muscle swelling": {},
//   "muscle weakness": {},
//   "nausea": {},
//   "neck pain": {},
//   "neurological signs": {},
//   "noisy breathing": {},
//   "nosebleeds": {},
//   "oral pain": {},
//   "osteoarthritis": {},
//   "pain in lower back": {},
//   "pale gums": {},
//   "panting": {},
//   "paralysis": {},
//   "pawing at face": {},
//   "petechiae": {},
//   "petechiae on skin": {},
//   "poor growth": {},
//   "pot-belly": {},
//   "prolonged bleeding after surgery or injury": {},
//   "proteinuria (foamy urine)": {},
//   "rapid breathing": {},
//   "rapid heart rate": {},
//   "recurrent infections": {},
//   "red gums": {},
//   "redness": {},
//   "reduced activity": {},
//   "reduced appetite": {},
//   "reduced flexibility": {},
//   "reluctance to chew": {},
//   "reluctance to jump": {},
//   "reluctance to move": {},
//   "restlessness": {},
//   "retching": {},
//   "scooting": {},
//   "scratching at air": {},
//   "scratching at neck": {},
//   "sensitivity to touch": {},
//   "sensory deficits": {},
//   "shifting leg lameness": {},
//   "shivering": {},
//   "skin infections": {},
//   "skin inflammation": {},
//   "skin irritation": {},
//   "skin scaling": {},
//   "skin thickening": {},
//   "skipping gait": {},
//   "sores": {},
//   "sound sensitivity": {},
//   "spontaneous bleeding": {},
//   "staggering": {},
//   "stiffness": {},
//   "stunted growth": {},
//   "sudden carrying of leg": {},
//   "sunken eyes": {},
//   "swelling": {},
//   "swelling at infection site": {},
//   "swelling below eye": {},
//   "swollen gums": {},
//   "swollen joints": {},
//   "swollen lymph nodes": {},
//   "tail paralysis": {},
//   "thirst": {},
//   "ticks": {},
//   "tremors": {},
//   "unsteadiness": {},
//   "unsteady gait": {},
//   "unusual behavior": {},
//   "unusual eye movements": {},
//   "vaginal discharge": {},
//   "visible mites": {},
//   "vocalization when touched": {},
//   "voice changes": {},
//   "von willebrand disease": {},
//   "waddling gait": {},
//   "weakness": {},
//   "weight gain": {},
//   "wide-legged stance": {},
//   "wobbling": {},
//   "wobbly gait": {},
//   "worms in stool": {},
//   "worn toenails": {},
//   "yellow gums": {},
//   "yellow skin": {}
// };
