final Map<String, dynamic> symptomQuestions = {
  "vomiting": {
    "questions": [
      "How long has your pet had vomiting?",
      "Is the vomiting Mild or Severe?"
    ],
    "impactDays": ["1-4 days", "5-7 days"],
    "impactSymptom": ["mild", "severe"],
  },
  "diarrhea": {
    "questions": [
      "How long has your pet had diarrhea?",
      "Is the diarrhea Watery or Bloody?"
    ],
    "impactDays": ["1-4 days", "5-7 days"],
    "impactSymptom": ["watery", "bloody"],
  },
  "coughing": {
    "questions": [
      "How long has your pet had coughing?",
      "Is the coughing Dry or Wet?"
    ],
    "impactDays": ["1-4 days", "5-7 days", "8-14 days", "persistent"],
    "impactSymptom": ["dry", "wet"],
  },
  "fever": {
    "questions": [
      "How long has your pet had fever?",
      "Is the fever Mild, Moderate, or Severe?"
    ],
    "impactDays": ["1-4 days", "5-7 days", "8-14 days"],
    "impactSymptom": ["mild", "moderate", "severe"],
  },
  "lethargy": {
    "questions": [
      "How long has your pet had lethargy?",
      "Is the lethargy Mild or Severe?"
    ],
    "impactDays": ["1-2 days", "3-5 days", "6-10 days", "11+ days", "variable"],
    "impactSymptom": ["mild", "severe", "variable"],
  },
  "eye discharge": {
    "questions": [
      "How long has your pet had eye discharge?",
      "Is the eye discharge Watery or Mucous-like?"
    ],
    "impactDays": ["1-2 days", "3-10 days"],
    "impactSymptom": ["watery", "mucous-like"],
  },
  "nasal discharge": {
    "questions": [
      "How long has your pet had nasal discharge?",
      "Is the nasal discharge Clear or Purulent?"
    ],
    "impactDays": ["1-2 days", "3-10 days"],
    "impactSymptom": ["clear", "purulent"],
  },
  "muscle twitching": {
    "questions": [
      "How long has your pet had muscle twitching?",
      "Is the muscle twitching Mild or Severe?"
    ],
    "impactDays": ["1-2 days", "3-5 days", "6-10 days", "11+ days"],
    "impactSymptom": ["mild", "severe", "variable"],
  },
  "seizures": {
    "questions": [
      "How long has your pet had seizures?",
      "Are the seizures Partial or Generalized?"
    ],
    "impactDays": ["1-2 days", "3-5 days", "6-10 days", "11+ days", "generalized"],
    "impactSymptom": ["partial", "generalized", "intermittent", "progressive", "chronic"],
  },
  "sneezing": {
    "questions": [
      "How long has your pet had sneezing?",
      "Is the sneezing Intermittent?"
    ],
    "impactDays": ["1-2 days", "3-5 days", "6-10 days"],
    "impactSymptom": ["intermittent"],
  },
  "muscle paralysis": {
    "questions": [
      "How long has your pet had muscle paralysis?",
      "Is the muscle paralysis Ascending?"
    ],
    "impactDays": ["1-2 days", "3-5 days", "6-10 days", "11+ days", "irreversible"],
    "impactSymptom": ["ascending", "irreversible"],
  },

  "abdominal discomfort": {},
  "abdominal enlargement": {},
  "abdominal pain": {},
  "abnormal breeding behavior": {},
  "abnormal posture": {},
  "abscesses": {},
  "aggression": {},
  "anemia": {},
  "anxiety": {},
  "arched back": {},
  "back pain": {},
  "back stiffness": {},
  "bad breath": {},
  "behavioral changes": {},
  "bleeding": {},
  "bleeding gums": {},
  "blindness": {},
  "bloating": {},
  "blood in urine": {},
  "bluish gums": {},
  "breathing difficulty": {},
  "bruising": {},
  "bunny hopping": {},
  "cataracts": {},
  "circling": {},
  "collapse": {},
  "confusion": {},
  "confusion post-seizure": {},
  "coordination issues": {},
  "dandruff": {},
  "dark stool": {},
  "dark urine": {},
  "decreased appetite": {},
  "dehydration": {},
  "depression": {},
  "diabetes mellitus": {},
  "difficulty breathing": {},
  "difficulty chewing": {},
  "difficulty eating": {},
  "difficulty moving": {},
  "difficulty moving elbow": {},
  "difficulty opening mouth": {},
  "difficulty rising": {},
  "difficulty running": {},
  "difficulty standing": {},
  "difficulty swallowing": {},
  "difficulty urinating": {},
  "difficulty walking": {},
  "discolored teeth": {},
  "disorientation": {},
  "distended abdomen": {},
  "draining wounds": {},
  "drooling": {},
  "dropping food": {},
  "dull coat": {},
  "ear discharge": {},
  "ear odor": {},
  "ear scratching": {},
  "edema (swelling)": {},
  "enlarged jaw": {},
  "enlarged lymph nodes": {},
  "enlarged testicles": {},
  "excessive bleeding": {},
  "excessive bleeding from minor wounds": {},
  "excessive crying": {},
  "excessive drooling": {},
  "excessive scratching": {},
  "exercise intolerance": {},
  "eye inflammation": {},
  "facial abnormalities": {},
  "facial swelling": {},
  "fainting": {},
  "falling over": {},
  "fatigue": {},
  "fearfulness": {},
  "flea dirt": {},
  "fleas": {},
  "foot dragging": {},
  "forelimb lameness": {},
  "frequent urination": {},
  "gagging": {},
  "hair loss": {},
  "head shaking": {},
  "head tilt": {},
  "head tremors": {},
  "hind limb atrophy": {},
  "hindlimb lameness": {},
  "hip pain": {},
  "hoarse bark": {},
  "hunched back": {},
  "hypothermia": {},
  "incontinence": {},
  "increased appetite": {},
  "increased thirst": {},
  "increased urination": {},
  "inflamed gums": {},
  "inflammation": {},
  "intermittent lameness": {},
  "intermittent limping": {},
  "irritability": {},
  "itching": {},
  "jaundice": {},
  "jaw pain": {},
  "joint pain": {},
  "joint swelling": {},
  "lameness": {},
  "light sensitivity": {},
  "limb swelling": {},
  "loose teeth": {},
  "loss of appetite": {},
  "loss of consciousness": {},
  "loss of coordination": {},
  "loss of muscle mass": {},
  "loss of reflexes": {},
  "mouth ulcers": {},
  "muscle atrophy": {},
  "muscle pain": {},
  "muscle swelling": {},
  "muscle weakness": {},
  "nausea": {},
  "neck pain": {},
  "neurological signs": {},
  "noisy breathing": {},
  "nosebleeds": {},
  "oral pain": {},
  "osteoarthritis": {},
  "pain": {},
  "pain in lower back": {},
  "pale gums": {},
  "panting": {},
  "paralysis": {},
  "pawing at face": {},
  "petechiae": {},
  "petechiae on skin": {},
  "poor growth": {},
  "pot-belly": {},
  "prolonged bleeding after surgery or injury": {},
  "proteinuria (foamy urine)": {},
  "rapid breathing": {},
  "rapid heart rate": {},
  "recurrent infections": {},
  "red gums": {},
  "redness": {},
  "reduced activity": {},
  "reduced appetite": {},
  "reduced flexibility": {},
  "reluctance to chew": {},
  "reluctance to jump": {},
  "reluctance to move": {},
  "restlessness": {},
  "retching": {},
  "scooting": {},
  "scratching at air": {},
  "scratching at neck": {},
  "sensitivity to touch": {},
  "sensory deficits": {},
  "shifting leg lameness": {},
  "shivering": {},
  "skin infections": {},
  "skin inflammation": {},
  "skin irritation": {},
  "skin scaling": {},
  "skin thickening": {},
  "skipping gait": {},
  "sores": {},
  "sound sensitivity": {},
  "spontaneous bleeding": {},
  "staggering": {},
  "stiffness": {},
  "stunted growth": {},
  "sudden carrying of leg": {},
  "sunken eyes": {},
  "swelling": {},
  "swelling at infection site": {},
  "swelling below eye": {},
  "swollen gums": {},
  "swollen joints": {},
  "swollen lymph nodes": {},
  "tail paralysis": {},
  "thirst": {},
  "ticks": {},
  "tremors": {},
  "unsteadiness": {},
  "unsteady gait": {},
  "unusual behavior": {},
  "unusual eye movements": {},
  "vaginal discharge": {},
  "visible mites": {},
  "vocalization when touched": {},
  "voice changes": {},
  "von willebrand disease": {},
  "waddling gait": {},
  "weakness": {},
  "weight gain": {},
  "weight loss": {},
  "wide-legged stance": {},
  "wobbling": {},
  "wobbly gait": {},
  "worms in stool": {},
  "worn toenails": {},
  "yellow gums": {},
  "yellow skin": {}
};
