// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwYozG_MVK5W9hYNTwl_gYLutOks6IVxE',
    appId: '1:149494599473:ios:7b9cddd44e78f9259d6a10',
    messagingSenderId: '149494599473',
    projectId: 'petsymp-594e7',
    storageBucket: 'petsymp-594e7.firebasestorage.app',
    iosBundleId: 'com.example.petsymp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwYozG_MVK5W9hYNTwl_gYLutOks6IVxE',
    appId: '1:149494599473:ios:7b9cddd44e78f9259d6a10',
    messagingSenderId: '149494599473',
    projectId: 'petsymp-594e7',
    storageBucket: 'petsymp-594e7.firebasestorage.app',
    iosBundleId: 'com.example.petsymp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvfuIr4NkXBIL4nWk1RyDsXlcbVIE1nOw',
    appId: '1:149494599473:web:a8e406954961e4e89d6a10',
    messagingSenderId: '149494599473',
    projectId: 'petsymp-594e7',
    authDomain: 'petsymp-594e7.firebaseapp.com',
    storageBucket: 'petsymp-594e7.firebasestorage.app',
    measurementId: 'G-FXKDBJFSW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_Z6Kz-33lBEDHgXtHZBQ95jkH6eZFas0',
    appId: '1:149494599473:android:71b4bf4e98807baa9d6a10',
    messagingSenderId: '149494599473',
    projectId: 'petsymp-594e7',
    storageBucket: 'petsymp-594e7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvfuIr4NkXBIL4nWk1RyDsXlcbVIE1nOw',
    appId: '1:149494599473:web:66aba039579398e99d6a10',
    messagingSenderId: '149494599473',
    projectId: 'petsymp-594e7',
    authDomain: 'petsymp-594e7.firebaseapp.com',
    storageBucket: 'petsymp-594e7.firebasestorage.app',
    measurementId: 'G-GVZ53QYQDB',
  );

}