  final Map<String, String> symptomDescriptions = {
  "abdominal discomfort": "Mild unease in the stomach region.",
  "abdominal enlargement": "Noticeable increase in belly size.",
  "abdominal pain": "Cramping or aching in the abdomen.",
  "abnormal breeding behavior": "Deviation from typical mating actions.",
  "abnormal posture": "Atypical alignment of the body.",
  "abscesses": "Localized pus-filled lesions under the skin.",
  "aggression": "Hostile or combative demeanor.",
  "anemia": "Lower than normal red blood cell count.",
  "anxiety": "Restless or nervous behavior without obvious cause.",
  "arched back": "Upward arching of the spine.",
  "back pain": "Ache along the back or spine.",
  "back stiffness": "Reduced flexibility in the back.",
  "bad breath": "Unpleasant odor from the mouth.",
  "behavioral changes": "Alterations in typical activities or mood.",
  "bleeding": "Blood loss from vessels.",
  "bleeding gums": "Blood discharge from gum tissue.",
  "blindness": "Loss of vision partially or fully.",
  "bloating": "Swollen or distended abdomen.",
  "blood in urine": "Presence of blood discoloring urine.",
  "bluish gums": "Gums taking on a blue or purple hue.",
  "breathing difficulty": "Hard or labored breathing.",
  "bruising": "Skin discoloration from underlying bleeding.",
  "bunny hopping": "Rear legs moving together in a hopping fashion.",
  "cataracts": "Opaque spots on the eye lens.",
  "circling": "Repeat walking in circles.",
  "collapse": "Sudden inability to stand.",
  "confusion": "Disorientation or lack of awareness.",
  "confusion post-seizure": "Disorientation after seizure activity.",
  "coordination issues": "Unsteady control of movements.",
  'coughing': 'Sudden expulsion of air from the lungs to clear the passages.',
  "dandruff": "White flakes on the coat.",
  "dark stool": "Bowel movements darker than normal.",
  "dark urine": "Urine with an unusually deep color.",
  "decreased appetite": "Lower interest in eating.",
  "dehydration": "Significant loss of body fluids.",
  "depression": "Reduced engagement with environment.",
  'diarrhea': 'Loose, watery stools occurring more frequently than usual.',
  "difficulty breathing": "Struggle to inhale or exhale.",
  "difficulty chewing": "Problems biting or grinding food.",
  "difficulty eating": "Challenges in consuming food.",
  "difficulty moving": "Limited movement ability.",
  "difficulty moving elbow": "Restricted elbow joint motion.",
  "difficulty opening mouth": "Jaw cannot open fully.",
  "difficulty rising": "Trouble standing from rest.",
  "difficulty running": "Inability to run normally.",
  "difficulty standing": "Hard to maintain upright stance.",
  "difficulty swallowing": "Trouble passing food or liquid down throat.",
  "difficulty urinating": "Problems releasing urine.",
  "difficulty walking": "Impaired or hesitant gait.",
  "discolored teeth": "Teeth showing abnormal coloration.",
  "disorientation": "Disorientation refers to characterized by disorientation..",
  "distended abdomen": "Distended abdomen refers to characterized by distended abdomen..",
  "draining wounds": "Draining wounds refers to characterized by draining wounds..",
  "drooling": "Drooling refers to characterized by drooling..",
  "dropping food": "Dropping food refers to characterized by dropping food..",
  "dull coat": "Dull coat refers to characterized by dull coat..",
  "ear discharge": "Ear discharge refers to characterized by ear discharge..",
  "ear odor": "Ear odor refers to characterized by ear odor..",
  "ear scratching": "Ear scratching: sensation prompting scratching.",
  "edema (swelling)": "Edema (swelling): enlargement due to fluid or inflammation.",
  "enlarged jaw": "Enlarged jaw refers to characterized by enlarged jaw..",
  "enlarged lymph nodes": "Enlarged lymph nodes refers to characterized by enlarged lymph nodes..",
  "enlarged testicles": "Enlarged testicles refers to characterized by enlarged testicles..",
  "excessive bleeding": "Excessive bleeding: blood escaping from vessels.",
  "excessive bleeding from minor wounds": "Excessive bleeding from minor wounds: blood escaping from vessels.",
  "excessive crying": "Excessive crying refers to characterized by excessive crying..",
  "excessive drooling": "Excessive drooling refers to characterized by excessive drooling..",
  "excessive scratching": "Excessive scratching: sensation prompting scratching.",
  "exercise intolerance": "Exercise intolerance refers to characterized by exercise intolerance..",
  "eye discharge": "Eye discharge refers to characterized by eye discharge..",
  "eye inflammation": "Eye inflammation refers to characterized by eye inflammation..",
  "facial abnormalities": "Facial abnormalities refers to characterized by facial abnormalities..",
  "facial swelling": "Facial swelling: enlargement due to fluid or inflammation.",
  "fainting": "Fainting refers to characterized by fainting..",
  "falling over": "Falling over refers to characterized by falling over..",
  "fatigue": "Fatigue refers to characterized by fatigue..",
  "fearfulness": "Fearfulness refers to characterized by fearfulness..",
  'fever': 'Abnormally high body temperature, often indicating infection.',
  "flea dirt": "Flea dirt refers to characterized by flea dirt..",
  "fleas": "Fleas refers to characterized by fleas..",
  "foot dragging": "Foot dragging refers to characterized by foot dragging..",
  "forelimb lameness": "Forelimb lameness refers to characterized by forelimb lameness..",
  "frequent urination": "Frequent urination refers to characterized by frequent urination..",
  "gagging": "Gagging refers to characterized by gagging..",
  "hair loss": "Hair loss: loss of hair in a specific region.",
  "head shaking": "Head shaking refers to characterized by head shaking..",
  "head tilt": "Head tilt refers to characterized by head tilt..",
  "head tremors": "Head tremors refers to characterized by head tremors..",
  "hind limb atrophy": "Hind limb atrophy refers to characterized by hind limb atrophy..",
  "hindlimb lameness": "Hindlimb lameness refers to characterized by hindlimb lameness..",
  "hip pain": "Hip pain: experience of pain in the area.",
  "hoarse bark": "Hoarse bark refers to characterized by hoarse bark..",
  "hunched back": "Hunched back refers to characterized by hunched back..",
  "hypothermia": "Hypothermia refers to characterized by hypothermia..",
  "incontinence": "Incontinence refers to characterized by incontinence..",
  "increased appetite": "Increased appetite refers to characterized by increased appetite..",
  "increased thirst": "Increased thirst refers to characterized by increased thirst..",
  "increased urination": "Increased urination refers to characterized by increased urination..",
  "inflamed gums": "Inflamed gums refers to characterized by inflamed gums..",
  "inflammation": "Inflammation refers to characterized by inflammation..",
  "intermittent lameness": "Intermittent lameness refers to characterized by intermittent lameness..",
  "intermittent limping": "Intermittent limping refers to characterized by intermittent limping..",
  "irritability": "Irritability refers to characterized by irritability..",
  "itching": "Itching: sensation prompting scratching.",
  "jaundice": "Jaundice refers to characterized by jaundice..",
  "jaw pain": "Jaw pain: experience of pain in the area.",
  "joint pain": "Joint pain: experience of pain in the area.",
  "joint swelling": "Joint swelling: enlargement due to fluid or inflammation.",
  "lameness": "Lameness refers to characterized by lameness..",
  'lethargy': 'Unusual tiredness or decreased activity.',
  "light sensitivity": "Light sensitivity refers to characterized by light sensitivity..",
  "limb swelling": "Limb swelling: enlargement due to fluid or inflammation.",
  "loose teeth": "Loose teeth refers to characterized by loose teeth..",
  'loss of appetite': 'Reduced desire to eat despite a normal feeding schedule.',
  "loss of consciousness": "Period of unresponsiveness during which awareness of surroundings is lost.",
  "loss of coordination": "Impaired ability to perform controlled, harmonious movements.",
  "loss of muscle mass": "Gradual reduction in muscle size and strength over time.",
  "loss of reflexes": "Diminished automatic responses to external stimuli.",
  "mouth ulcers": "Mouth ulcers refers to characterized by mouth ulcers..",
  "muscle atrophy": "Muscle atrophy refers to characterized by muscle atrophy..",
  "muscle pain": "Muscle pain: experience of pain in the area.",
  "muscle paralysis": "Muscle paralysis refers to characterized by muscle paralysis..",
  "muscle swelling": "Muscle swelling: enlargement due to fluid or inflammation.",
  "muscle twitching": "Muscle twitching: sensation prompting scratching.",
  "muscle weakness": "Muscle weakness: reduced strength in affected area.",
  "nasal discharge": "Nasal discharge refers to characterized by nasal discharge..",
  "nausea": "Nausea refers to characterized by nausea..",
  "neck pain": "Neck pain: experience of pain in the area.",
  "neurological signs": "Neurological signs refers to characterized by neurological signs..",
  "noisy breathing": "Noisy breathing refers to characterized by noisy breathing..",
  "nosebleeds": "Nosebleeds refers to characterized by nosebleeds..",
  "oral pain": "Oral pain: experience of pain in the area.",
  "pain": "Pain: experience of pain in the area.",
  "pain in lower back": "Pain in lower back: experience of pain in the area.",
  "pale gums": "Pale gums refers to characterized by pale gums..",
  "panting": "Panting refers to characterized by panting..",
  "paralysis": "Paralysis refers to characterized by paralysis..",
  "pawing at face": "Pawing at face refers to characterized by pawing at face..",
  "petechiae": "Petechiae refers to characterized by petechiae..",
  "petechiae on skin": "Petechiae on skin refers to characterized by petechiae on skin..",
  "poor growth": "Poor growth refers to characterized by poor growth..",
  "pot-belly": "Pot-belly refers to characterized by pot-belly..",
  "prolonged bleeding after surgery or injury": "Prolonged bleeding after surgery or injury: blood escaping from vessels.",
  "proteinuria (foamy urine)": "Proteinuria (foamy urine) refers to characterized by proteinuria (foamy urine)..",
  "rapid breathing": "Rapid breathing refers to characterized by rapid breathing..",
  "rapid heart rate": "Rapid heart rate refers to characterized by rapid heart rate..",
  "recurrent infections": "Recurrent infections refers to characterized by recurrent infections..",
  "red gums": "Red gums refers to characterized by red gums..",
  "redness": "Redness refers to characterized by redness..",
  "reduced activity": "Reduced activity refers to characterized by reduced activity..",
  "reduced appetite": "Reduced appetite refers to characterized by reduced appetite..",
  "reduced flexibility": "Reduced flexibility refers to characterized by reduced flexibility..",
  "reluctance to chew": "Hesitation or refusal to use the jaws for chewing, often indicating mouth discomfort.",
  "reluctance to jump": "Unwillingness to propel the body into the air, as seen when avoiding elevated surfaces.",
  "reluctance to move": "Hesitation or refusal to change position or walk, suggesting stiffness or discomfort.",
  "restlessness": "Inability to remain still, marked by constant shifting, pacing, or repeated position changes.",
  "retching": "Involuntary heaving movements of the abdomen and throat, indicating attempts to vomit.",
  "scooting": "Dragging the hindquarters along the ground, typically to relieve anal or perianal irritation.",
  "scratching at air": "Rapid paw movements directed toward empty space, indicating discomfort in hard-to-reach areas.",
  "scratching at neck": "Repeated pawing or rubbing at the neck region, signaling itching or irritation there.",
  "seizures": "Seizures refers to characterized by seizures..",
  "sensitivity to touch": "Sensitivity to touch refers to characterized by sensitivity to touch..",
  "sensory deficits": "Sensory deficits refers to characterized by sensory deficits..",
  "shifting leg lameness": "Shifting leg lameness refers to characterized by shifting leg lameness..",
  "shivering": "Shivering refers to characterized by shivering..",
  "skin infections": "Skin infections refers to characterized by skin infections..",
  "skin inflammation": "Skin inflammation refers to characterized by skin inflammation..",
  "skin irritation": "Skin irritation refers to characterized by skin irritation..",
  "skin scaling": "Skin scaling refers to characterized by skin scaling..",
  "skin thickening": "Skin thickening refers to characterized by skin thickening..",
  "skipping gait": "Skipping gait refers to characterized by skipping gait..",
  "sneezing": "Sneezing refers to characterized by sneezing..",
  "sores": "Sores refers to characterized by sores..",
  "sound sensitivity": "Sound sensitivity refers to characterized by sound sensitivity..",
  "spontaneous bleeding": "Spontaneous bleeding: blood escaping from vessels.",
  "staggering": "Staggering refers to characterized by staggering..",
  "stiffness": "Stiffness refers to characterized by stiffness..",
  "stunted growth": "Stunted growth refers to characterized by stunted growth..",
  "sudden carrying of leg": "Sudden carrying of leg refers to characterized by sudden carrying of leg..",
  "sunken eyes": "Sunken eyes refers to characterized by sunken eyes..",
  "swelling": "Swelling: enlargement due to fluid or inflammation.",
  "swelling at infection site": "Swelling at infection site: enlargement due to fluid or inflammation.",
  "swelling below eye": "Swelling below eye: enlargement due to fluid or inflammation.",
  "swollen gums": "Swollen gums refers to characterized by swollen gums..",
  "swollen joints": "Swollen joints refers to characterized by swollen joints..",
  "swollen lymph nodes": "Swollen lymph nodes refers to characterized by swollen lymph nodes..",
  "tail paralysis": "Tail paralysis refers to characterized by tail paralysis..",
  "thirst": "Thirst refers to characterized by thirst..",
  "ticks": "Small, blood-feeding arachnids that attach to the skin, causing localized itching, redness, and potential skin irritation.",
  "tremors": "Tremors refers to characterized by tremors..",
  "unsteadiness": "Unsteadiness refers to characterized by unsteadiness..",
  "unsteady gait": "Unsteady gait refers to characterized by unsteady gait..",
  "unusual behavior": "Unusual behavior refers to characterized by unusual behavior..",
  "unusual eye movements": "Unusual eye movements refers to characterized by unusual eye movements..",
  "vaginal discharge": "Vaginal discharge refers to characterized by vaginal discharge..",
  "visible mites": "Visible mites refers to characterized by visible mites..",
  "vocalization when touched": "Vocalization when touched refers to characterized by vocalization when touched..",
  "voice changes": "Voice changes refers to characterized by voice changes..",
  'vomiting': 'Forceful expulsion of stomach contents through the mouth.',
  "waddling gait": "Waddling gait refers to characterized by waddling gait..",
  "weakness": "Weakness: reduced strength in affected area.",
  "weight gain": "Weight gain refers to characterized by weight gain..",
  "weight loss": "Weight loss refers to characterized by weight loss..",
  "wide-legged stance": "Wide-legged stance refers to characterized by wide-legged stance..",
  "wobbling": "Wobbling refers to characterized by wobbling..",
  "wobbly gait": "Wobbly gait refers to characterized by wobbly gait..",
  "worms in stool": "Worms in stool refers to characterized by worms in stool..",
  "worn toenails": "Worn toenails refers to characterized by worn toenails..",
  "yellow gums": "Yellow gums refers to characterized by yellow gums..",
  "yellow skin": "Yellow skin refers to characterized by yellow skin.."

  };