final List<Map<String, String>> catBreed = [
  {"breed": "Abyssinian", "img": "assets/BreedCat/abyssiniancat.png"},
  {"breed": "American Bobtail", "img": "assets/BreedCat/americanbobtail.png"},
  {"breed": "American Curl", "img": "assets/BreedCat/americancurl.png"},
  {"breed": "American Shorthair", "img": "assets/BreedCat/americanshorthair.png"},
  {"breed": "American Wirehair", "img": "assets/BreedCat/americanwirehair.png"},
  {"breed": "Balinese", "img": "assets/BreedCat/balinese.png"},
  {"breed": "Bengal", "img": "assets/BreedCat/bengal.png"},
  {"breed": "Birman", "img": "assets/BreedCat/birman.png"},
  {"breed": "Bombay", "img": "assets/BreedCat/bombay.png"},
  {"breed": "British Longhair", "img": "assets/BreedCat/britishlonghair.png"},
  {"breed": "British Shorthair", "img": "assets/BreedCat/britishshorthair.png"},
  {"breed": "Burmese", "img": "assets/BreedCat/burmese.png"},
  {"breed": "Burmilla", "img": "assets/BreedCat/burmilla.png"},
  {"breed": "Chartreux", "img": "assets/BreedCat/chartreux.png"},
  {"breed": "Cornish Rex", "img": "assets/BreedCat/cornishrex.png"},
  {"breed": "Devon Rex", "img": "assets/BreedCat/devonrex.png"},
  {"breed": "Egyptian Mau", "img": "assets/BreedCat/egyptianmau.png"},
  {"breed": "Exotic Shorthair", "img": "assets/BreedCat/exoticshorthair.png"},
  {"breed": "Himalayan", "img": "assets/BreedCat/himalayan.png"},
  {"breed": "Japanese Bobtail", "img": "assets/BreedCat/japanesebobtail.png"},
  {"breed": "Khao Manee", "img": "assets/BreedCat/khaomanee.png"},
  {"breed": "LaPerm", "img": "assets/BreedCat/laperm.png"},
  {"breed": "Maine Coon", "img": "assets/BreedCat/mainecoon.png"},
  {"breed": "Manx", "img": "assets/BreedCat/manx.png"},
  {"breed": "Munchkin", "img": "assets/BreedCat/munchkin.png"},
  {"breed": "Norwegian Forest", "img": "assets/BreedCat/norwegianforest.png"},
  {"breed": "Ocicat", "img": "assets/BreedCat/ocicat.png"},
  {"breed": "Oriental", "img": "assets/BreedCat/oriental.png"},
  {"breed": "Persian", "img": "assets/BreedCat/persian.png"},
  {"breed": "Ragdoll", "img": "assets/BreedCat/ragdoll.png"},
  {"breed": "Russian Blue", "img": "assets/BreedCat/russianblue.png"},
  {"breed": "Scottish Fold", "img": "assets/BreedCat/scottishfold.png"},
  {"breed": "Siamese", "img": "assets/BreedCat/siamese.png"},
  {"breed": "Siberian", "img": "assets/BreedCat/siberian.png"},
  {"breed": "Singapura", "img": "assets/BreedCat/singapura.png"},
  {"breed": "Snowshoe", "img": "assets/BreedCat/snowshoe.png"},
  {"breed": "Somali", "img": "assets/BreedCat/sumali.png"}, // spelling corrected for image file
  {"breed": "Sphynx", "img": "assets/BreedCat/sphynx.png"},
  {"breed": "Tonkinese", "img": "assets/BreedCat/tonkinese.png"},
  {"breed": "Toyger", "img": "assets/BreedCat/toyger.png"},
  {"breed": "Turkish Angora", "img": "assets/BreedCat/turkishangora.png"},
  {"breed": "Turkish Van", "img": "assets/BreedCat/turkishvan.png"},
];
