final List<Map<String, String>> dogBreed = [
  {"breed": "Akita", "img": "assets/Breed/akita.png"},
  {"breed": "Alaskan Malamute", "img": "assets/Breed/alaskanmalamute.png"},
  {"breed": "American Bulldog", "img": "assets/Breed/americanbulldog.png"},
  {"breed": "American Eskimo", "img": "assets/Breed/americaneskimo.png"},
  {"breed": "Australian Cattle", "img": "assets/Breed/australiancattle.png"},
  {"breed": "Australian Shepherd", "img": "assets/Breed/australianshepperd.png"},
  {"breed": "Basset Hound", "img": "assets/Breed/bassethound.png"},
  {"breed": "Beagle", "img": "assets/Breed/beagle.png"},
  {"breed": "Belgian Malinois", "img": "assets/Breed/belgianmalinois.png"},
  {"breed": "Bernese Mountain", "img": "assets/Breed/bernesemountain.png"},
  {"breed": "Bichon Frise", "img": "assets/Breed/bichonfrise.png"},
  {"breed": "Border Collie", "img": "assets/Breed/bordercollie.png"},
  {"breed": "Boston Terrier", "img": "assets/Breed/bostonterrier.png"},
  {"breed": "Boxer", "img": "assets/Breed/boxer.png"},
  {"breed": "Bulldog", "img": "assets/Breed/bulldog.png"},
  {"breed": "Bull Terrier", "img": "assets/Breed/bullterrier.png"},
  {"breed": "Cairn Terrier", "img": "assets/Breed/cairnterrier.png"},
  {"breed": "Cavalier King Charles Spaniel", "img": "assets/Breed/kingcharles.png"},
  {"breed": "Chihuahua", "img": "assets/Breed/Chihuahua.png"},
  {"breed": "Chow Chow", "img": "assets/Breed/chowchow.png"},
  {"breed": "Cocker Spaniel", "img": "assets/Breed/cockerspaniel.png"},
  {"breed": "Collie", "img": "assets/Breed/collie.png"},
  {"breed": "Corgi", "img": "assets/Breed/corgi.png"},
  {"breed": "Dachshund", "img": "assets/Breed/dachshund.png"},
  {"breed": "Dalmatian", "img": "assets/Breed/dalmatian.png"},
  {"breed": "Doberman Pinscher", "img": "assets/Breed/dobermanpinscher.png"},
  {"breed": "English Setter", "img": "assets/Breed/englishsetter.png"},
  {"breed": "English Springer Spaniel", "img": "assets/Breed/englishspringer.png"},
  {"breed": "Finnish Spitz", "img": "assets/Breed/finnishspitz.png"},
  {"breed": "French Bulldog", "img": "assets/Breed/frenchbulldog.png"},
  {"breed": "German Shepherd", "img": "assets/Breed/germanshepherd.png"},
  {"breed": "Golden Retriever", "img": "assets/Breed/goldenretriever.png"},
  {"breed": "Great Dane", "img": "assets/Breed/greatdane.png"},
  {"breed": "Greyhound", "img": "assets/Breed/greyhound.png"},
  {"breed": "Havanese", "img": "assets/Breed/havanese.png"},
  {"breed": "Irish Setter", "img": "assets/Breed/irishsetter.png"},
  {"breed": "Italian Greyhound", "img": "assets/Breed/italiangreyhound.png"},
  {"breed": "Jack Russell Terrier", "img": "assets/Breed/JRTerrier.png"},
  {"breed": "Japanese Chin", "img": "assets/Breed/japanesechin.png"},
  {"breed": "Keeshond", "img": "assets/Breed/keeshond.png"},
  {"breed": "Komondor", "img": "assets/Breed/komondor.png"},
  {"breed": "Labrador Retriever", "img": "assets/Breed/labradorretriever.png"},
  {"breed": "Lhasa Apso", "img": "assets/Breed/lhasaapso.png"},
  {"breed": "Maltese", "img": "assets/Breed/maltese.png"},
  {"breed": "Mastiff", "img": "assets/Breed/mastiff.png"},
  {"breed": "Miniature Pinscher", "img": "assets/Breed/miniaturepincher.png"},
  {"breed": "Miniature Schnauzer", "img": "assets/Breed/miniatureschnauzer.png"},
  {"breed": "Newfoundland", "img": "assets/Breed/newfoundland.png"},
  {"breed": "Norwegian Elkhound", "img": "assets/Breed/norwegianelkhound.png"},
  {"breed": "Papillon", "img": "assets/Breed/papillion.png"},
  {"breed": "Pekingese", "img": "assets/Breed/pekingese.png"},
  {"breed": "Pembroke Welsh Corgi", "img": "assets/Breed/pembrokewelshcorgi.png"},
  {"breed": "Pomeranian", "img": "assets/Breed/pomerian.png"},
  {"breed": "Poodle", "img": "assets/Breed/poodle.png"},
  {"breed": "Pug", "img": "assets/Breed/pug.png"},
  {"breed": "Rhodesian Ridgeback", "img": "assets/Breed/rhodesianridgeback.png"},
  {"breed": "Rottweiler", "img": "assets/Breed/rottwailer.png"},
  {"breed": "Saint Bernard", "img": "assets/Breed/saintbernard.png"},
  {"breed": "Samoyed", "img": "assets/Breed/samoyed.png"},
  {"breed": "Schipperke", "img": "assets/Breed/schipperke.png"},
  {"breed": "Schnauzer", "img": "assets/Breed/schnauzer.png"},
  {"breed": "Scottish Terrier", "img": "assets/Breed/scottishterrier.png"},
  {"breed": "Shar Pei", "img": "assets/Breed/sharpei.png"},
  {"breed": "Shetland Sheepdog", "img": "assets/Breed/shetlandsheepdog.png"},
  {"breed": "Shiba Inu", "img": "assets/Breed/shibainu.png"},
  {"breed": "Shih Tzu", "img": "assets/Breed/ShihTzu.png"},
  {"breed": "Siberian Husky", "img": "assets/Breed/siberianhusky.png"},
  {"breed": "Staffordshire Bull Terrier", "img": "assets/Breed/staffordshirebullterrier.png"},
  {"breed": "Toy Poodle", "img": "assets/Breed/toypoodle.png"},
  {"breed": "Welsh Terrier", "img": "assets/Breed/welshterrier.png"},
  {"breed": "West Highland White Terrier", "img": "assets/Breed/westhighlandwhiteterrier.png"},
  {"breed": "Yorkshire Terrier", "img": "assets/Breed/yorkshireterrier.png"},
];
